#!/bin/sh

<<0
        ::::::::: :::::::::::   :::   :::   :::::::::
       :+:    :+:    :+:      :+:+: :+:+:  :+:    :+:
      +:+    +:+    +:+     +:+ +:+:+ +:+ +:+    +:+
     +#++:++#+     +#+     +#+  +:+  +#+ +#++:++#+
    +#+           +#+     +#+       +#+ +#+
   #+#           #+#     #+#       #+# #+#
  ###       ########### ###       ### ###

                            raspberry pi music player
                                      -- -     -
0

DPATH_MUSIC="${DPATH_MUSIC-"$HOME/Music"}"
FPATH_PLAYLIST="${FPATH_PLAYLIST-"$HOME/.cache/pimp.playlist"}"
prereq="pimp espeak ffplay mpv"

export DPATH_MUSIC
export FPATH_PLAYLIST

check_prereq()
{
	local result=0

	printf '%s' "$*" | sed 's/$/\n/g' | sed 's/ /\n/g' | \
	while read -r i
	do
		if ! command -v "${i}" > /dev/null 2>&1
		then
			result=1
			printf 'pimp: prerequisite "%s" not found\n' "${i}" >&2
		fi
	done

	return "${result}"
}

create_list()
{
	# description: generates recursive file list of specified directory
	#              and saves output as playlist file.

	mkdir "$(dirname "${FPATH_PLAYLIST}")" > /dev/null 2>&1

	if [ -d "${DPATH_MUSIC}/$*" ]
	then
		local dpath_full="$(realpath "${DPATH_MUSIC}/$*")"
		find -L "${dpath_full}" -type f | sort > "${FPATH_PLAYLIST}"
	fi
}

item_play()
{
	# description: plays playlist file.

	pkill espeak
	pkill ffplay

	if ! [ -z "$*" ]
	then
		for i in "$*"
		do
			create_list "${i}"
			break
		done
	fi

	if [ -f "${FPATH_PLAYLIST}" ]
	then
		clear
		printf 'pimp: initiating the slap... (⌐■_■)\n\n'

		item_sound play

		mpv \
			--audio-pitch-correction=no --af-add=scaletempo=speed=both \
			--display-tags= \
			--loop-file=no \
			--loop-playlist=inf \
			--no-audio-display \
			--no-video \
			--playlist="${FPATH_PLAYLIST}" \
			--save-position-on-quit \
			--shuffle \
			"$@"
	else
		printf 'pimp: cannot find %s\n' "${FPATH_PLAYLIST}" >&2
		return 1
	fi
}

item_sound()
{
	# description: produces sound effects for auditory guidance /
	#              navigation.

	case "$@" in
		select)
			ffplay -f lavfi -i 'sine=frequency=2000:duration=0.025' \
				-autoexit -nodisp > /dev/null 2>&1
			;;
		play)
			ffplay -f lavfi -i 'sine=frequency=1000:duration=0.025' \
				-autoexit -nodisp > /dev/null 2>&1
			;;
		*)
			ffplay -f lavfi -i 'sine=frequency=2000:duration=0.025' \
				-autoexit -nodisp > /dev/null 2>&1
			;;
	esac
}

list_dirs()
{
	clear

	find -L "${DPATH_MUSIC}" -type d -printf '%P\n' | sort -r | sed '/^$/d' | sed '$a.' | \
	fzf -i -s -m -e \
		--header='pimp' \
		--header-first \
		--border=rounded \
		--color=fg:7,bg:0,fg+:0,bg+:10,hl:9,hl+:1,border:10,gutter:0,header:10,prompt:7,info:10 \
		--prompt '> ' \
		--algo=v1 \
		--literal \
		--cycle \
		--tac \
		--no-mouse \
		--header-lines=0 \
		--layout=reverse \
		--preview '(printf "%s" {} | sed "s/\//, /g" | espeak -a 250 -s 300 && ffplay -f lavfi -i "sine=frequency=2000:duration=0.025" -nodisp -autoexit)' \
		--preview-window 0% \
		--bind "enter:execute(pimp play {})" \
		--bind 'change:first' \
		--bind 'backward-eof:execute-silent(printf clear | espeak -a 250 -s 300)' \
		--bind 'bspace:clear-query' \
		--bind 'home:first' \
		--bind 'end:last' \
		--bind 'insert:abort' \
		--bind 'alt-q:abort' \
		--bind 'ctrl-q:abort' \
		--bind 'tab:abort'
}

list_filter()
{
	modtime_pimp_list_pre="$(stat --format '%Y' "${FPATH_PLAYLIST}")"

	clear
	item_sound select

	find -L "${DPATH_MUSIC}" -type f -printf '%P\n' | sort -r | sed '/^$/d' | \
	fzf -i -s -m -e \
		--header='pimp' \
		--header-first \
		--border=rounded \
		--color=fg+:0,bg+:10,hl:9,hl+:1,border:10,gutter:0,header:10,prompt:7,info:10 \
		--prompt '> ' \
		--algo=v1 \
		--literal \
		--cycle \
		--tac \
		--no-mouse \
		--header-lines=0 \
		--layout=reverse \
		--bind 'enter:select-all+accept+execute(rm -f "${FPATH_PLAYLIST}")' \
		--bind 'change:first' \
		--bind 'backward-eof:execute-silent(printf clear | espeak -a 250 -s 300)' \
		--bind 'home:first' \
		--bind 'end:last' \
		--bind 'insert:abort' \
		--bind 'alt-q:abort' \
		--bind 'ctrl-q:abort' \
		--bind 'tab:abort' | \
	while read -r f
	do
		printf '%s/%s\n' "${DPATH_MUSIC}" "$f" >> "${FPATH_PLAYLIST}"
		continue
	done

	modtime_pimp_list_post="$(stat --format '%Y' "${FPATH_PLAYLIST}")"

	if [ "${modtime_pimp_list_post}" != "${modtime_pimp_list_pre}" ]
	then
		item_play
	fi
}

if ! check_prereq "${prereq}"
then
	exit 1
fi

if ! [ -d "${DPATH_MUSIC}" ]
then
	printf 'pimp: music directory not found: %s\n' "${DPATH_MUSIC}" >&2
	exit 1
fi

case "$1" in
	dirs|-d)
		list_dirs
		exit
		;;
	
	filter|-f)
		list_filter
		exit
		;;

	play|slap|-p)
		item_play "$2"
		exit $?
		;;

	play-sound)
		item_sound "$2"
		exit 
		;;
	
	*)
		if [ -f "${FPATH_PLAYLIST}" ]
		then
			item_play
		fi

		list_dirs
		exit
		;;
esac
