#!/bin/bash -ue

print-logo()
{
	cat <<EOF

          ::::::::: :::::::::::   :::   :::   :::::::::
         :+:    :+:    :+:      :+:+: :+:+:  :+:    :+:
        +:+    +:+    +:+     +:+ +:+:+ +:+ +:+    +:+
       +#++:++#+     +#+     +#+  +:+  +#+ +#++:++#+
      +#+           +#+     +#+       +#+ +#+
     #+#           #+#     #+#       #+# #+#
    ###       ########### ###       ### ###

                              raspberry pi music player
                                        -- -     -
EOF

	return 0
}

print-startup-sound-data()
{
	#  audio/opus data (base64).

	cat <<EOF
T2dnUwACAAAAAAAAAABwWWSDAAAAAEHGn5ABE09wdXNIZWFkAQE4AYC7AAAAAABPZ2dTAAAAAAAA
AAAAAHBZZIMBAAAAhKKhKAE+T3B1c1RhZ3MNAAAATGF2ZjU4LjQ1LjEwMAEAAAAdAAAAZW5jb2Rl
cj1MYXZjNTguOTEuMTAwIGxpYm9wdXNPZ2dTAASpVgAAAAAAAHBZZIMCAAAAKTaVeRn/HJyk5v6w
p/8tq5+qsLLenv6creXqvOjU+J9w3jzG0vOxAxaYAj4owahZJcCLRXV5PFr5JqJzI87dTh4pQqUj
PON8VmM0s2q9jOgk2m2QlVstq7PRL8RWtd5ELx2aekRTr97qfFCFAHF/cQtGvnD3T3G0ddNskwXW
vVF4eIDFWQrVLuzn+AxM6jERURxJSwcWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAC03/TPhAcoDSC8R3heI7w2tWwQSFIqIc+g9PxIta9mvVIlLsXqCsBlS67L2ScaiIYY2
5YJ3QUXTP036rFX6ApD5QXKuFuOOh3WgQ8fnhwgvGucHDsiy5eKcs50EVl+hi/CNkSpCCa5dXgFH
oR/uFC+XbWp7uaudyWQwsfidbIqEGupY1TlHRXbI/AL4yf25eyKhpW0KazD+mKnmN6SFIO5ggnhX
hqSqr51jLOz2oFIUYRXFWaafLAUV6kGJcOeVEmVy8wuEAI2pwmeeGzkJMjsL5e5v34NompdHUJo8
jr2wTqGyiFucaKlryeOS5hgdsSDV1TE5oCWc5/StK6MhhG0w4VLHLK3D5ieF5YX4IFd2DYLvb4sw
0fidLklPdErSMmK8zqRsPjFXq9wB/Aw2KLD0JlcxIlqEo/5Mro9RvoMjfxNNlX7Q7udIDyPgP4H8
mkh/pa1hOrI61DeftEqIGDEU3oYKhNeE/hJ8drmN+bS7U99gtpzls+dEOW3bp4nrwKrfNlrgwEny
41a6ju3dC15PoJeNVxTZkvMVqgrgZaI3Lwvi0bH73q+oS89NqX+9mKilkqcKT8dDgb3R+PKC8/d0
StI1FmZolYtm3i6zRJjeYvsI2ziC9dnLFvx8FPiXE2VkBePkR/NAyvJEMu7WPEqKxUvHQBPp8wYV
rUR0NNhLj4GvHv9xyqaSFgFphbtJTdKdEkKlDxD3jfEojLWP6lwg44d3XFaxPmL3IcneTBLD80vB
hYsUbHa77Q+preTBbnQj9Vb9Qm8uTvI78tHXC8tpgGUPHaaFyd1XI3DI+MF6i3G01TnlyRuEsYvX
3rfNeNX/NI7bmTf252SAR47qW84JsRI7iOZRCZb9yZwYpAEv2vc+mJCfiUqdN7iKtKH0fTH4nS5J
T3RK0jJjow2mcL/4BlKGrHOtR6wxA6QhVJ5Apg+wVo2cf6n60CbjpZeHxR04DRGaLeEZzgYBWv/N
mWiiE7/cGQr+bcuSIUdPfJwQLJc8xeCVj5tf2I2l3F9hs/0ceHaqu5YkfZarJcvddPEUVkbnoQrF
JOSUlJaw8DRCahHoqqVAAFpeF+KwehyXG6bAL5tgME6UVwsEks4DgwGY4X5dsmMwhQvfx34CWjUg
ncWOnmsRN2Jbz3asOnqiZIrJ/G7ShHx2F1W9iRxLRDDtj9wExWaYuqpsexcDH3YkMkG4mNpMr3ZU
CBik/tfumdMuoDBTGVem11EqSx9F0fij689UxgzPm704zb4gFdqLY7pTAZ6JE8cULqHhyoWp7HdA
GONZs2XieSkOCA9eZeUfRGqXrZOBsx1eEiyQgdr3xIa5/Y/1PtsqcDw71KVX3OYXoxQ9jUimUDNp
7myX1nsk0uLd+n9+JQrVKkJdwEX9rEfTOobWAlLh4KwrY3E3LXk+pbu2sSZjDFbJEMbFaPtWEOGO
GqYYXCakI35BI+VfN6xFk4aYSrk2un6ZB1LR+KlBGf7GDM+cB/SDzzlpwn4ZMdvWOFqrtGMgYmVl
0Sw31lrkZ2Ps1OsY42DErWPrtKh/th/0UAFN96443/9rY2kD60awMx7g4XKf4Ojx37/60CiX62Xe
kCfm0s1zmdv6kt+BDDgiLKKO83YTR5E+bLXBgDc0ItAmU/cqygl4zDA7auKbMl5mbpwDn1sfLGyO
ja/e9XwkfK/Hs+yvgUwlX6SbQ0yDStH4v5CuMR0aTOLWKTaE2OsEy9jl+WYAZJd8wiFCzhVuwAda
EpxT9ok0uFgpjI6BYYNmu8EleXm6lAUtVwVEyFFi+5uIoqH0zcbTDsRJVvhV0PYUd/YU0S1OVJ2H
PLvN4gBP7y8wwrjoz91a4pOaYaNGr4Idf/Sn6Ui0f7YLx+/b+gdWd42e+MEGn4SFdNn1hREixIAA
AAAAAShyFs1TW6cnoOkM9o/XaNmO4BEv+3zAIDxW5U5A5h/w6bwOJkeURvqwivEHRuN5tkuHldBF
KP5+gVNC65X+OzRZWsKqlqLQSsV1+3zF5XGgvl8oE2Ufj4DDkUffmpwcrRMx7Dj8Zk1ivDqqYUTa
aGFjvJ1Dho5W/KprcDQ5nxQPJc6UJyaXBsYBx0GDePy2lrvaN6H4qfoEdSVqSUhQG1G0hdzvOrof
6+EfhzDhMdNHHpTianKsWnoXEjX8o7wF22vc2RLQkGDYelCRC7nUzhtwhUM6U5krxL1rrPSVXoKJ
7JOhJPOFs24ofPD1/2MzsCFCx0JlRFrntWEvk/vH0OMchoRzKZTEBRrVCW84ccJDMRrenczbG06a
hIrEU+fPZwmrWvi946P4lcvvSv8JFfiOVh6fUjoMbbrJeSpWMMH4qVitnBagnPLJ4lMzySSOVEF/
k2kYnygDDlbyt+mI8vrNmnA31CtRt0VGJrPypnqd/cPyjWq/LqCOJGxhj/nRFhil1fj5G64lH2r/
0CIgPT+PxD0OHmP+0SlCHWowmhIyihj6w1rLt3UumSgfWx691V7qDIYjKbdt3Rd+uAdPZAGiuk/4
SbzvDsvvB6XJF6t6nxGHWr9J0UAjIxJv8cH4qWArFvlj+PyNjYMQcok9aOc44hqqfWz6Z7FylHTQ
ZFXGS7ajDxjP+V5kV4c+FZH2dU0nKuv8S00Z/LbVQtRVtLUSanXImJarDh4Mz+Zhml4fm3OM48Dq
+7YwOMgKjvwfa5MGCSXzfoKK6mwIVdMlFSMOqzy+Rxlq0HJFmyGSrchIneZ1Ld+3PZiDv/SvJ2GN
RoT+N/BPjyslCfzGlLoq/ScE4FYiEm/nwfipYCsW+WPZ3ERglwTUcdJrhq3PaioYSndVysvdy7uB
9C3UK3lrL1McaJithYj73HawVKDpy23AkXRPnVQjCmreTXzRkJ+JUkfhJsyu8pNLZwQhSVlyxYQ0
vEZzDcNVmPF5MADaVUJrkwaO/B/H97UhR/gaa//F0yUVIw10yaARQJUSM0MlW5CRMKDlEmpXP53/
pXljC9N9K/G/T+fwTV+wlw1l/NX6TgwIViMOb+bB+KlgKxb5Y9ncRGCXBNRx0muGrc9qLEpYgChI
Fi+pWaMcj46Pv3AjCGdr/LFHvT1ivhUv6e/jVQbiLVYOWXJxFVnBg0Un2/Vez3BBLGipBkJ7dKay
5YiTCXJaZzDsPViPF4EwAPV5p478J2uTBnEuhmn0FfA01/+a6ZHyqmOqzyD/rTNCyM0MlW5CRI6D
lK+pXP50JpXljC9N9K/G/if7wTV+wlwvowVXuk4MBFYiDm/lwfi+tWSqD5hdWN8QVTm6Fcam0tvu
hBYkGOkepY3FglmmtHIg8y67EPu1YwrLQFcQNMEXWUDEvgBVhFHKNLToxYQrFGlWbpAhymNbsz32
fp3/40/C38k5zdqd2BohrLGcuBSFnF0OXBK0iVflAIkaqxY+DV72F0GY3vURaLUtEv053SsnNK47
J4Hrp0m/wO0GQUx9VZ2mT5u+ouwj0ZbcQ3xoyTV7HcOTKwws2NQKkIq2QmuPVq9nfKALtCWMqmhJ
ranXhgd7QgaNzA2hGRJWGOczywZKclNaHBJU5uTRgvi+tWHiYjE36rfkLB0h2aPHod30y3qjiFuj
6b02swfqEfS0kq71i2md4808B9nbtNVApMXoUZwybgCkRo+vzy85riWQy2WhjTMYoDLflhFF43cp
c/d+QdvrHl28QMs1q+ZcfWowUHkpPH6d9etgdIDJEwpWhzyx0/z+p/LuMpQJ9NjvldRVzLQl+7nx
bF3r8g1YJz+Fq0X9130gfN2C+I9ohEP2eWFIrduN3uG3HLDCVKPpyml99enq7UkyvsvCASJRjbji
eNP9ISeESjXBpcdotG/2V0gwvKPVYQnr0l6MqAvaBna8SV2Eh5BcE2DltAZCXVFIYzeSxVdtvVpv
m7aqr2m+Bl9IT1k0KWhDrDjvBclrTlF8Ya3DHNJbDK9DilV8SaI+xZa2i63qJoxjLb2aGXcBQpga
3OpUnndpI/aUQgoE9uZMo3Pdds/CKVTTG9TzC3qHh8hNt0wufXzoGz/gOgfc1KrZ6ZfzdR8W5G3D
0rPgUHAh9cm9cm+fyD4IrELqDsd7dMz5NtDe0WHpPl6FdB6i+qAAmF1/Wkn4j1HMK/e20Aqf28H1
6rXrlb2LTkF6Z6W4pNCSsGCVzgYxpIBB6IfGg+GUjqGbvi3SpLM9Dk69AdgFWfyo1KY3HW4gwsLK
nR6dQzm9+Go/yVBXsd+UroUh6evubygVVtgSeoHPTnl4OD2SU4PYjRUdFw5aGctPofCieUzSpFkY
EzNG9Deqf7G2leGZUOZfbytqor9nSuaZ+p6aCun4sssCQ+20+mXaSaY58MXMaijuSzhjg7Fhh7lm
DJhkLH0PCyhdSQ1XZVUXUVNXtKmKiKY/MVK1l8Res3SmmdUvRrgEtRjHaeLwvCOJszpW0ZddUBiv
NHyF8o/xrY3i6H9H00smf4aUKIlFqQiXY/bA5ZrBMlWWdrU4jo60cf2UIiFSZClg/Qmf49gj4v1z
4AQYwt460ds4uYwr/ewViHIl9JLKZDGQYl8+OXV9ofjddVeanMlLCQfY5t6gYxj6eSQwC/CRPhcL
7dy1zNB/AwDpFnZ96HPwU82ES8+CbikMlsOFFAjEB68JIpV9efnJGE/ToCzb8lTJpQCrrRbwc4qm
vMlV7vHB47MWfX/00IJCzDH61ilmk+9k1THBxiXTadPIt9kwH9j19O5xNUGaqMngXnKUYHOyv5ay
dWf84P0/Zp0fMoPXa3LHyf04ff3Y9xQRK84iDryKTrreR+5MktzIwPPm913H2Os+IFhrHREn1Y7V
txBW7bb8C9uk92Vg7lmbusruJu7NMhbpVJnfTgqrxsn4iB/Xq723GTHUAAdEu3oi1LCWeTyQK5Re
mgTHlf9L16jqNDA3Lbu+IfTvNp8qaUNLEFze/4WgnJ5vtHQ6T3FcSFIOye6VSjoFub9/BfIG5A3q
VyjAPyIMyv41OrS1w49XIpCBZDWnj2a+yLt/Le7Nq2uqzjXy1BfVNZOiMGzaczL7crokbi/Pfpxr
sdmubOvmVru+q/FE9B4/LyG1fbYpCJdd0zm/8SBn6BamuvInJx7cmTbUpN1rNz3TVm9MpaRZua5S
dv1Y7VtwOcOf/U2LSQJG1i3Ps1u6yuSXqtsFTIW6VRZ6ZS82BWn4iCCs7efQhj0ipF6kbxXuQas/
IFkAuE2nlA8GWR82+vmVh9cdnvTcMA+1FPTPLTHfKpKaVo8IySyAgQueFqEVbA1wtqBC6QtUMrZH
fBODZASE53j23wDwzVl7sU81WTFHWQIZAkFCsWTI7zcAtsf+kGMO4Zk2ALTcfwTJUuz0wwNu1RgB
7R6jOaqUfXZBEdsqORFXZ8B0sLEjV1t99C68V+edOIkU7R+X1mDw9Q9s8jDJiC3SqDPOkeV+afid
dQJXvbcZMdQAB0KKYc7v1HMNJxhkVe9YzzgMqRn/qeHKtQGjxQlxChYFZ4DC104D/TGvwvN4hl+I
9cwmmhD76MgWL02dDtXbkAvjU+LlHjjGZrNIIAszHPF72uXK7+ky/XJxho8aDBWEc1vwsAzUzXRD
QvILOHwW3lopi5R7lKKtZHDj8E0vFmL3dJJgdWyd0jQh+oPH5fQE1SPFIQIqQzxcUH9RF9ifLryJ
ycd3JkxX4DNUcTZp978zqVNC4ly6lN6x2hf96d+c+34PSQJB1BufZrd1lcmqSOZwkQv0aozx0l6s
CNH4hsRK4VUZ2n69N1CVXK9E47RJfF2ntgR6Ato5jPU/u0dVabAqn2miugcNSy6z+4tGqd1mpTuX
xAXoFLbWxMW4DYca+HLDcOaonelks+H+42+f1QWH20fXluhsHoIFi+aqUcik+xRhAjzVHbjpRoAo
RBesSMT9+Op1zRS8AsRFFLcYzTphAyXEermycDe8irwloksbvAtVeZITUuYaaF7DG1W1nHWffVEF
OmJgQUEZr+e7kBFqNiGPnbkJ9ZOO1t6z/tAaDmZs4L5dKmalIJ8oKjGQaQ==
EOF
}

if ! [ -d "${HOME}/Music" ]
then
	mkdir "${HOME}/Music" > /dev/null 2>&1
fi

if [ "$(tty)" = '/dev/tty1' ] && command -v pimp > /dev/null 2>&1
then
	clear
	print-logo

	if ! [ -f "${HOME}/startup.opus" ]
	then
		print-startup-sound-data | base64 -d > "${HOME}/startup.opus"
	fi

	if [ -f "${HOME}/startup.opus" ]
	then
		mpv --really-quiet --loop-file=no --volume=150 "${HOME}/startup.opus" > /dev/null 2>&1
	fi

	while :
	do
		tmux new-session -n 'pimp' -d 'pimp -q'
		tmux -2 attach
	done
fi
